import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

import { colors } from '../src/colors.ts';
import { containerWidths } from '../src/containerWidths.ts';
import { shadows } from '../src/effects.ts';
import { spacing } from '../src/spacing.ts';
import {
  fontFamilies,
  fontSizes,
  fontWeights,
  textPresets,
} from '../src/typography.ts';

const themeFilePath = fileURLToPath(
  new URL('../src/theme.css', import.meta.url)
);

const generatedFileNotice =
  '/* This file is generated by scripts/generate-css.ts. Do not edit directly. */';

type CssDeclaration = readonly [name: string, value: string];

const toKebabCase = (value: string) =>
  value
    .replace(/([a-z])([A-Z])/g, '$1-$2')
    .replace(/([a-zA-Z])([0-9])/g, '$1-$2')
    .toLowerCase();

const toRem = (px: number) => `${px / 16}rem`;

const toPx = (px: number) => (px === 0 ? '0' : `${px}px`);

const toShadowCssName = (name: string) =>
  name.endsWith('Shadow') ? name.slice(0, -'Shadow'.length) : name;

const createRootDeclarations = (): CssDeclaration[] => [
  ...Object.entries(colors).map(
    ([name, value]) =>
      [`--bearnance-color-${toKebabCase(name)}`, value] as const
  ),
  ...Object.entries(fontFamilies).map(
    ([name, value]) =>
      [
        `--bearnance-font-family-${toKebabCase(name)}`,
        `'${value}', sans-serif`,
      ] as const
  ),
  ...Object.entries(fontSizes).map(
    ([name, value]) =>
      [`--bearnance-font-size-${toKebabCase(name)}`, toRem(value)] as const
  ),
  ...Object.entries(fontWeights).map(
    ([name, value]) =>
      [`--bearnance-font-weight-${toKebabCase(name)}`, String(value)] as const
  ),
  ...Object.entries(fontSizes).map(([name]) => {
    const textPresetName = name as keyof typeof textPresets;

    return [
      `--bearnance-line-height-${toKebabCase(name)}`,
      toRem(textPresets[textPresetName].lineHeight),
    ] as const;
  }),
  ...Object.entries(shadows).map(
    ([name, value]) =>
      [
        `--bearnance-shadow-${toKebabCase(toShadowCssName(name))}`,
        `${toPx(value.offsetX)} ${toPx(value.offsetY)} ${toPx(value.blur)} ${toPx(value.spread)} ${value.color}`,
      ] as const
  ),
  ...Object.entries(spacing).map(
    ([name, value]) =>
      [`--bearnance-spacing-${toKebabCase(name)}`, toRem(value)] as const
  ),
  ...Object.entries(containerWidths).map(
    ([name, value]) =>
      [`--bearnance-container-${toKebabCase(name)}`, toRem(value)] as const
  ),
];

const toTailwindThemeVariableName = (
  cssVariableName: string
): string | null => {
  const prefix = '--bearnance-';

  if (!cssVariableName.startsWith(prefix)) {
    return null;
  }

  const tokenName = cssVariableName.slice(prefix.length);

  if (
    tokenName.startsWith('color-') ||
    tokenName.startsWith('container-') ||
    tokenName.startsWith('font-weight-') ||
    tokenName.startsWith('shadow-') ||
    tokenName.startsWith('spacing-')
  ) {
    return `--${tokenName}`;
  }

  if (tokenName.startsWith('font-family-')) {
    return `--font-${tokenName.slice('font-family-'.length)}`;
  }

  if (tokenName.startsWith('font-size-')) {
    return `--${tokenName.slice('font-size-'.length)}`;
  }

  if (tokenName.startsWith('line-height-')) {
    return `--${tokenName.slice('line-height-'.length)}--line-height`;
  }

  return null;
};

const renderCssDeclarations = (
  declarations: ReadonlyArray<readonly [string, string]>
) => declarations.map(([name, value]) => `  ${name}: ${value};`).join('\n');

const renderThemeCss = () => {
  const rootDeclarations = createRootDeclarations();
  const tailwindThemeDeclarations = rootDeclarations
    .map(([cssVariableName]) => {
      const tailwindThemeVariableName =
        toTailwindThemeVariableName(cssVariableName);

      if (tailwindThemeVariableName === null) {
        return null;
      }

      return [tailwindThemeVariableName, `var(${cssVariableName})`] as const;
    })
    .filter((declaration) => declaration !== null);

  return `${generatedFileNotice}

:root {
${renderCssDeclarations(rootDeclarations)}
}

@theme inline {
${renderCssDeclarations(tailwindThemeDeclarations)}
}
`;
};

const checkThemeCss = async (expectedThemeCss: string) => {
  const currentThemeCss = await readFile(themeFilePath, 'utf8');

  if (currentThemeCss === expectedThemeCss) {
    return;
  }

  console.error(
    'Generated theme CSS is stale. Run `pnpm --filter @bearnance/design-tokens generate:css`.'
  );
  process.exitCode = 1;
};

const main = async () => {
  const args = new Set(process.argv.slice(2));
  const shouldCheck = args.has('--check');

  if (args.size > (shouldCheck ? 1 : 0)) {
    console.error('Usage: node scripts/generate-css.ts [--check]');
    process.exitCode = 1;
    return;
  }

  const themeCss = renderThemeCss();

  if (shouldCheck) {
    await checkThemeCss(themeCss);
    return;
  }

  await writeFile(themeFilePath, themeCss);
};

await main();
