import { existsSync } from 'node:fs';
import { mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { basename, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { format, resolveConfig } from 'prettier';

import { transform } from '@svgr/core';

const svgDir = fileURLToPath(new URL('../icons/svg', import.meta.url));
const brandManifestPath = fileURLToPath(
  new URL('../src/brand-icons.generated.ts', import.meta.url)
);
const webGenDir = fileURLToPath(
  new URL('../../ui-web/src/components/icons/generated', import.meta.url)
);
const nativeGenDir = fileURLToPath(
  new URL('../../ui-mobile/src/components/icons/generated', import.meta.url)
);

const header = [
  '/* Generated by @bearnance/ui-core scripts/generate-icons.ts. Do not edit directly. */',
  '/* To regenerate: pnpm --filter @bearnance/ui-core gen:icons */',
].join('\n');

const svgoConfig = (platform: 'web' | 'native') => ({
  plugins: [
    {
      name: 'preset-default',
      params: {
        overrides: {
          removeViewBox: false,
          convertColors: { currentColor: true },
        },
      },
    },
    'removeDimensions',
    // `react-native-svg`'s <Svg> has no `xmlns` prop, so drop it for native.
    ...(platform === 'native' ? ['removeXMLNS'] : []),
  ],
});

const toPascalCase = (value: string) =>
  value
    .split(/[-_]/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');

const componentName = (iconName: string) => `${toPascalCase(iconName)}Icon`;

const prettyPrint = async (filePath: string, source: string) => {
  const config = await resolveConfig(filePath);

  return format(source, { ...config, filepath: filePath });
};

const renderComponent = async (
  svg: string,
  iconName: string,
  platform: 'web' | 'native'
) => {
  const code = await transform(
    svg,
    {
      plugins: ['@svgr/plugin-svgo', '@svgr/plugin-jsx'],
      typescript: true,
      jsxRuntime: 'automatic',
      prettier: false,
      native: platform === 'native',
      icon: platform === 'web',
      svgo: true,
      svgoConfig: svgoConfig(platform),
    },
    { componentName: componentName(iconName) }
  );

  return `${header}\n\n${code}`;
};

const renderRegistry = (iconNames: string[], platform: 'web' | 'native') => {
  const propsType = platform === 'web' ? 'SVGProps<SVGSVGElement>' : 'SvgProps';
  const propsImport =
    platform === 'web'
      ? "import type { ComponentType, SVGProps } from 'react';"
      : "import type { ComponentType } from 'react';\nimport type { SvgProps } from 'react-native-svg';";
  const imports = iconNames
    .map(
      (name) => `import ${componentName(name)} from './${componentName(name)}';`
    )
    .join('\n');
  const entries = iconNames
    .map((name) => `  '${name}': ${componentName(name)},`)
    .join('\n');

  return `${header}

${propsImport}

import type { BrandIconName } from '@bearnance/ui-core/icon';

${imports}

export const brandIconRegistry: Record<
  BrandIconName,
  ComponentType<${propsType}>
> = {
${entries}
};
`;
};

const renderManifest = (iconNames: string[]) => {
  const names = iconNames.map((name) => `  '${name}',`).join('\n');

  return `${header}

export const brandIconNames = [
${names}
] as const;
`;
};

/** Files that should exist after a full generation, keyed by absolute path. */
const buildOutputs = async (
  iconNames: string[],
  svgByName: Map<string, string>
) => {
  const outputs = new Map<string, string>();

  outputs.set(
    brandManifestPath,
    await prettyPrint(brandManifestPath, renderManifest(iconNames))
  );

  for (const [dir, platform] of [
    [webGenDir, 'web'],
    [nativeGenDir, 'native'],
  ] as const) {
    for (const name of iconNames) {
      const filePath = join(dir, `${componentName(name)}.tsx`);
      const source = await renderComponent(
        svgByName.get(name)!,
        name,
        platform
      );

      outputs.set(filePath, await prettyPrint(filePath, source));
    }

    const registryPath = join(dir, 'registry.ts');

    outputs.set(
      registryPath,
      await prettyPrint(registryPath, renderRegistry(iconNames, platform))
    );
  }

  return outputs;
};

const readSvgs = async () => {
  const files = (await readdir(svgDir))
    .filter((file) => file.endsWith('.svg'))
    .sort();
  const svgByName = new Map<string, string>();

  for (const file of files) {
    const name = basename(file, '.svg');

    svgByName.set(name, await readFile(join(svgDir, file), 'utf8'));
  }

  return { iconNames: [...svgByName.keys()], svgByName };
};

/** Remove stale generated `.ts`/`.tsx` files no longer backed by an SVG. */
const pruneDir = async (dir: string, keep: Set<string>) => {
  if (!existsSync(dir)) {
    return;
  }

  for (const file of await readdir(dir)) {
    if (
      (file.endsWith('.tsx') || file.endsWith('.ts')) &&
      !keep.has(join(dir, file))
    ) {
      await rm(join(dir, file));
    }
  }
};

const write = async (outputs: Map<string, string>) => {
  await Promise.all([
    mkdir(webGenDir, { recursive: true }),
    mkdir(nativeGenDir, { recursive: true }),
  ]);

  const keep = new Set(outputs.keys());

  await pruneDir(webGenDir, keep);
  await pruneDir(nativeGenDir, keep);

  for (const [filePath, content] of outputs) {
    await writeFile(filePath, content);
  }
};

const check = async (outputs: Map<string, string>) => {
  const stale: string[] = [];

  for (const [filePath, content] of outputs) {
    if (
      !existsSync(filePath) ||
      (await readFile(filePath, 'utf8')) !== content
    ) {
      stale.push(filePath);
    }
  }

  if (stale.length > 0) {
    console.error(
      'Generated icon files are stale. Run `pnpm --filter @bearnance/ui-core gen:icons`.\n' +
        stale.map((file) => `  - ${file}`).join('\n')
    );
    process.exitCode = 1;
  }
};

const main = async () => {
  const shouldCheck = process.argv.slice(2).includes('--check');
  const { iconNames, svgByName } = await readSvgs();
  const outputs = await buildOutputs(iconNames, svgByName);

  if (shouldCheck) {
    await check(outputs);
    return;
  }

  await write(outputs);
};

await main();
